/**
 * Curated job-title aliases for career-graph roles.
 *
 * The graph speaks in Indian qualification/pathway language ("Software Job (IT)",
 * "Data Entry Operator") while scraped postings use industry titles ("Backend
 * Engineer", "Site Reliability Engineer"). Token overlap alone cannot bridge that,
 * so these explicit mappings do the heavy lifting; the strict matcher in
 * @career-maps/core refuses to guess beyond them.
 *
 * Keys are role slugs. Add entries here and re-run `npm run rematch` to reclassify
 * postings already in the database — no re-scraping needed.
 */
export const ROLE_ALIASES: Record<string, string[]> = {
  "software-job-it": [
    "Software Engineer",
    "Software Developer",
    "Backend Engineer",
    "Backend Developer",
    "Frontend Engineer",
    "Frontend Developer",
    "Full Stack Engineer",
    "Full Stack Developer",
    "Web Developer",
    "Mobile Engineer",
    "iOS Engineer",
    "Android Engineer",
    "Application Developer",
    "Programmer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "QA Engineer",
    "Test Engineer",
    "Software Architect",
    "Security Engineer",
    "Systems Engineer",
  ],
  "business-analytics": [
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Analytics Engineer",
    "Business Analyst",
    "BI Analyst",
    "Business Intelligence Analyst",
    "Machine Learning Engineer",
    "ML Engineer",
    "AI Engineer",
    "Research Scientist",
  ],
  marketing: [
    "Marketing Specialist",
    "Marketing Manager",
    "Digital Marketer",
    "Digital Marketing Manager",
    "Growth Marketer",
    "Growth Manager",
    "SEO Specialist",
    "Content Marketer",
    "Content Writer",
    "Copywriter",
    "Social Media Manager",
    "Performance Marketing Manager",
    "Brand Manager",
  ],
  finance: [
    "Financial Analyst",
    "Finance Manager",
    "Accountant",
    "Bookkeeper",
    "Financial Controller",
    "Controller",
    "Auditor",
    "Payroll Specialist",
  ],
  "data-entry-operator": ["Data Entry Clerk", "Data Entry Specialist", "Data Entry Associate", "Transcriptionist"],
  "call-center-job": [
    "Customer Support Specialist",
    "Customer Support Representative",
    "Customer Service Representative",
    "Customer Success Manager",
    "Technical Support Specialist",
    "Support Engineer",
    "Help Desk Technician",
    "Call Center Agent",
  ],
  hr: [
    "Recruiter",
    "Technical Recruiter",
    "Talent Acquisition Specialist",
    "HR Manager",
    "HR Generalist",
    "People Operations Manager",
    "People Partner",
  ],
  "operations-management": ["Operations Manager", "Operations Specialist", "Business Operations Manager", "Operations Analyst"],
  "business-management": ["Product Manager", "Project Manager", "Program Manager", "Product Owner", "Chief of Staff"],
  "logistics-management": ["Logistics Coordinator", "Supply Chain Manager", "Warehouse Manager", "Fulfilment Coordinator"],
  "photo-editing": ["Photo Editor", "Photo Retoucher", "Graphic Designer", "Visual Designer", "Video Editor"],
  teacher: ["Teacher", "Tutor", "Instructor", "Lecturer", "Teaching Assistant"],
  "event-management": ["Event Manager", "Event Coordinator", "Event Producer"],
  "insurance-probationary": ["Insurance Agent", "Underwriter", "Claims Adjuster"],
  "hotel-management-degree": ["Hotel Manager", "Hospitality Manager", "Front Desk Manager"],
  librarian: ["Librarian", "Library Assistant"],
  bank: ["Bank Teller", "Relationship Manager", "Loan Officer", "Credit Analyst"],
};
